{% set version = "4.0.0a28" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: 175fa948d1ad9c2a48a05baeafd08b2ab7459b44a4131b9db0a9e1d05c1b14dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --install-option="--skip-npm" . -vv
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main
    - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - build
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.2.0
    - pip
    - pre-commit
    - python >=3.7
  run:
    - async-lru >=1.0.0
    - importlib_metadata >=3.6
    - importlib_resources >=1.4
    - ipykernel
    - jinja2 >=3.0.3
    - jupyter_core
    - jupyter-lsp >=1.5.1
    - jupyter_server >=1.16.0,<2
    - jupyter_server_ydoc >=0.1.9,<0.2.0
    - jupyterlab_server >=2.11.1,<3
    - notebook-shim >=0.1
    - packaging
    - python >=3.7
    - traitlets
    - tornado >=6.1.0
    - tomli
    - ypy-websocket

test:
  requires:
    - nodejs >=14,!=15.*,<17
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab
  commands:
    - pip check
    - jupyter lab --version
    - jlpm --version
    - jlpm versions
    - jupyter labextension list
    - jupyter lab licenses
    - jupyter lab path
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter lab build --dev-build=False --minimize=False --verbose=1
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio
